version: '2.1'
orbs:
  docker: circleci/docker@2.0.3
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - docker/check
      - docker/build:
          image: naoyer/node
      - docker/push:
          digest-path: /tmp/digest.txt
          image: naoyer/node
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push

